---
http_interactions:
- request:
    method: get
    uri: http://ohana-api-test.herokuapp.com/api/search?action=index&controller=organizations&keyword=asdfg&location=&utf8=%E2%9C%93
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/vnd.ohanapi-v1+json
      User-Agent:
      - Ohanakapa Ruby Gem 1.0.0
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 200
      message: OK
    headers:
      Cache-Control:
      - max-age=0, private, must-revalidate
      Content-Type:
      - application/json; charset=utf-8
      Date:
      - Sat, 05 Jul 2014 10:41:33 GMT
      Link:
      - <http://ohana-api-test.herokuapp.com/api/search?keyword=asdfg&location=&page=0&utf8=%E2%9C%93>;
        rel="last"
      Server:
      - nginx/1.6.0 + Phusion Passenger 4.0.45
      Status:
      - 200 OK
      X-Content-Type-Options:
      - nosniff
      X-Frame-Options:
      - SAMEORIGIN
      X-Powered-By:
      - Phusion Passenger 4.0.45
      X-Request-Id:
      - f2fc2e8a-fd0c-4e97-9be6-dab81fa697c8
      X-Runtime:
      - '0.012344'
      X-Total-Count:
      - '0'
      X-Total-Pages:
      - '0'
      X-Xss-Protection:
      - 1; mode=block
      Content-Length:
      - '34'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: "[]"
    http_version: 
  recorded_at: Sat, 05 Jul 2014 10:41:34 GMT
- request:
    method: get
    uri: http://ohana-api-test.herokuapp.com/api/search?action=index&controller=organizations&utf8=%E2%9C%93
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/vnd.ohanapi-v1+json
      User-Agent:
      - Ohanakapa Ruby Gem 1.0.0
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 200
      message: OK
    headers:
      Cache-Control:
      - max-age=0, private, must-revalidate
      Content-Type:
      - application/json; charset=utf-8
      Date:
      - Sat, 05 Jul 2014 10:41:34 GMT
      Link:
      - <http://ohana-api-test.herokuapp.com/api/search?page=22&utf8=%E2%9C%93>; rel="last",
        <http://ohana-api-test.herokuapp.com/api/search?page=2&utf8=%E2%9C%93>; rel="next"
      Server:
      - nginx/1.6.0 + Phusion Passenger 4.0.45
      Status:
      - 200 OK
      X-Content-Type-Options:
      - nosniff
      X-Current-Page:
      - '1'
      X-Frame-Options:
      - SAMEORIGIN
      X-Next-Page:
      - '2'
      X-Powered-By:
      - Phusion Passenger 4.0.45
      X-Request-Id:
      - a0dd18dc-ccf6-46dc-bf39-9a17ff4df877
      X-Runtime:
      - '0.022100'
      X-Total-Count:
      - '22'
      X-Total-Pages:
      - '22'
      X-Xss-Protection:
      - 1; mode=block
      Transfer-Encoding:
      - chunked
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: '[{"id":1,"admin_emails":[],"coordinates":[-122.213221,37.477227],"description":"A
        walk-in center for older adults that provides social services, wellness, recreational,
        educational and creative activities including arts and crafts, computer classes
        and gardening classes. Coffee and healthy breakfasts are available daily.
        A hot lunch is served Tuesday-Friday for persons age 60 or over and spouse.        Provides
        case management (including in-home assessments) and bilingual information
        and referral about community services to persons age 60 or over on questions
        of housing, employment, household help, recreation and social activities,
        home delivered meals, health and counseling services and services to shut-ins.
        Health insurance and legal counseling is available by appointment. Lectures
        on a variety of health and fitness topics are held monthly in both English
        and Spanish.  Provides a variety of physical fitness opportunities, including
        a garden club, yoga, tai chi, soul line dance and aerobics classes geared
        toward older adults. Also provides free monthly blood pressure screenings,
        quarterly blood glucose monitoring and health screenings by a visiting nurse.
        Offers a Brown Bag Program in which low-income seniors can receive a bag of
        groceries each week for a membership fee of $10 a year. Offers Spanish lessons.
        Formerly known as Peninsula Family Service, Fair Oaks Intergenerational Center.
        Formerly known as the Fair Oaks Senior Center. Formerly known as Family Service
        Agency of San Mateo County, Fair Oaks Intergenerational Center.","latitude":37.477227,"longitude":-122.213221,"name":"Fair
        Oaks Adult Activity Center","short_desc":"A multipurpose senior citizens''
        center serving the Redwood City area.","slug":"fair-oaks-adult-activity-center","updated_at":"2014-05-09T20:49:18.836-07:00","urls":["http://www.peninsulafamilyservice.org"],"contacts_url":"http://ohana-api-test.herokuapp.com/api/locations/fair-oaks-adult-activity-center/contacts","faxes_url":"http://ohana-api-test.herokuapp.com/api/locations/fair-oaks-adult-activity-center/faxes","services_url":"http://ohana-api-test.herokuapp.com/api/locations/fair-oaks-adult-activity-center/services","url":"http://ohana-api-test.herokuapp.com/api/locations/fair-oaks-adult-activity-center","address":{"id":1,"street":"2600
        Middlefield Road","city":"Redwood City","state":"CA","zip":"94063"},"organization":{"id":1,"name":"Peninsula
        Family Service","slug":"peninsula-family-service","urls":[],"url":"http://ohana-api-test.herokuapp.com/api/organizations/peninsula-family-service","locations_url":"http://ohana-api-test.herokuapp.com/api/organizations/peninsula-family-service/locations"},"phones":[{"id":1,"department":null,"extension":null,"number":"650
        780-7525","number_type":null,"vanity_number":null}]}]'
    http_version: 
  recorded_at: Sat, 05 Jul 2014 10:41:34 GMT
- request:
    method: get
    uri: http://ohana-api-test.herokuapp.com/api/search?action=index&controller=organizations&page=3
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/vnd.ohanapi-v1+json
      User-Agent:
      - Ohanakapa Ruby Gem 1.0.0
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 200
      message: OK
    headers:
      Cache-Control:
      - max-age=0, private, must-revalidate
      Content-Type:
      - application/json; charset=utf-8
      Date:
      - Sat, 05 Jul 2014 10:41:35 GMT
      Link:
      - <http://ohana-api-test.herokuapp.com/api/search?page=1>; rel="first", <http://ohana-api-test.herokuapp.com/api/search?page=2>;
        rel="prev", <http://ohana-api-test.herokuapp.com/api/search?page=22>; rel="last",
        <http://ohana-api-test.herokuapp.com/api/search?page=4>; rel="next"
      Server:
      - nginx/1.6.0 + Phusion Passenger 4.0.45
      Status:
      - 200 OK
      X-Content-Type-Options:
      - nosniff
      X-Current-Page:
      - '3'
      X-Frame-Options:
      - SAMEORIGIN
      X-Next-Page:
      - '4'
      X-Powered-By:
      - Phusion Passenger 4.0.45
      X-Previous-Page:
      - '2'
      X-Request-Id:
      - bdb2c67e-7bb7-44d0-a12d-5d5dd5b66f1a
      X-Runtime:
      - '0.023881'
      X-Total-Count:
      - '22'
      X-Total-Pages:
      - '22'
      X-Xss-Protection:
      - 1; mode=block
      Content-Length:
      - '913'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: '[{"id":3,"admin_emails":[],"coordinates":[-122.3263232,37.5639394],"description":"Offers
        supportive counseling services to San Mateo County residents age 55 or over.
        Volunteer counselors are selected and professionally trained to help their
        peers face the challenges and concerns of growing older.  Training provides
        topics that include understanding depression, cultural competence, sexuality,
        community resources, and other subjects that are relevant to working with
        older adults. After completion of training, weekly supervision groups are
        provided for the volunteer senior peer counselors, as well as quarterly in-service
        training seminars. Peer counseling services are provided in English, Spanish,
        Chinese (Cantonese and Mandarin), Tagalog, and to the lesbian, gay, bisexual,
        transgender older adult community. Formerly known as Family Service Agency
        of San Mateo County, Senior Peer Counseling.","latitude":37.5639394,"longitude":-122.3263232,"name":"Senior
        Peer Counseling","short_desc":"Offers supportive counseling services to older
        persons.","slug":"senior-peer-counseling","updated_at":"2014-05-09T20:49:18.871-07:00","urls":[],"contacts_url":"http://ohana-api-test.herokuapp.com/api/locations/senior-peer-counseling/contacts","faxes_url":"http://ohana-api-test.herokuapp.com/api/locations/senior-peer-counseling/faxes","services_url":"http://ohana-api-test.herokuapp.com/api/locations/senior-peer-counseling/services","url":"http://ohana-api-test.herokuapp.com/api/locations/senior-peer-counseling","address":{"id":3,"street":"24
        Second Avenue","city":"San Mateo","state":"CA","zip":"94403"},"organization":{"id":1,"name":"Peninsula
        Family Service","slug":"peninsula-family-service","urls":[],"url":"http://ohana-api-test.herokuapp.com/api/organizations/peninsula-family-service","locations_url":"http://ohana-api-test.herokuapp.com/api/organizations/peninsula-family-service/locations"},"phones":[{"id":3,"department":"English","extension":null,"number":"650
        403-4300","number_type":null,"vanity_number":null}]}]'
    http_version: 
  recorded_at: Sat, 05 Jul 2014 10:41:35 GMT
- request:
    method: get
    uri: http://ohana-api-test.herokuapp.com/api/search?action=index&controller=organizations&org_name=Peninsula%20Family%20Service&utf8=%E2%9C%93
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/vnd.ohanapi-v1+json
      User-Agent:
      - Ohanakapa Ruby Gem 1.0.0
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 200
      message: OK
    headers:
      Cache-Control:
      - max-age=0, private, must-revalidate
      Content-Type:
      - application/json; charset=utf-8
      Date:
      - Sat, 05 Jul 2014 10:41:35 GMT
      Link:
      - <http://ohana-api-test.herokuapp.com/api/search?org_name=Peninsula+Family+Service&page=5&utf8=%E2%9C%93>;
        rel="last", <http://ohana-api-test.herokuapp.com/api/search?org_name=Peninsula+Family+Service&page=2&utf8=%E2%9C%93>;
        rel="next"
      Server:
      - nginx/1.6.0 + Phusion Passenger 4.0.45
      Status:
      - 200 OK
      X-Content-Type-Options:
      - nosniff
      X-Current-Page:
      - '1'
      X-Frame-Options:
      - SAMEORIGIN
      X-Next-Page:
      - '2'
      X-Powered-By:
      - Phusion Passenger 4.0.45
      X-Request-Id:
      - c88213e6-c236-4f35-9605-b3ac7a9b5441
      X-Runtime:
      - '0.027819'
      X-Total-Count:
      - '5'
      X-Total-Pages:
      - '5'
      X-Xss-Protection:
      - 1; mode=block
      Transfer-Encoding:
      - chunked
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: '[{"id":1,"admin_emails":[],"coordinates":[-122.213221,37.477227],"description":"A
        walk-in center for older adults that provides social services, wellness, recreational,
        educational and creative activities including arts and crafts, computer classes
        and gardening classes. Coffee and healthy breakfasts are available daily.
        A hot lunch is served Tuesday-Friday for persons age 60 or over and spouse.        Provides
        case management (including in-home assessments) and bilingual information
        and referral about community services to persons age 60 or over on questions
        of housing, employment, household help, recreation and social activities,
        home delivered meals, health and counseling services and services to shut-ins.
        Health insurance and legal counseling is available by appointment. Lectures
        on a variety of health and fitness topics are held monthly in both English
        and Spanish.  Provides a variety of physical fitness opportunities, including
        a garden club, yoga, tai chi, soul line dance and aerobics classes geared
        toward older adults. Also provides free monthly blood pressure screenings,
        quarterly blood glucose monitoring and health screenings by a visiting nurse.
        Offers a Brown Bag Program in which low-income seniors can receive a bag of
        groceries each week for a membership fee of $10 a year. Offers Spanish lessons.
        Formerly known as Peninsula Family Service, Fair Oaks Intergenerational Center.
        Formerly known as the Fair Oaks Senior Center. Formerly known as Family Service
        Agency of San Mateo County, Fair Oaks Intergenerational Center.","latitude":37.477227,"longitude":-122.213221,"name":"Fair
        Oaks Adult Activity Center","short_desc":"A multipurpose senior citizens''
        center serving the Redwood City area.","slug":"fair-oaks-adult-activity-center","updated_at":"2014-05-09T20:49:18.836-07:00","urls":["http://www.peninsulafamilyservice.org"],"contacts_url":"http://ohana-api-test.herokuapp.com/api/locations/fair-oaks-adult-activity-center/contacts","faxes_url":"http://ohana-api-test.herokuapp.com/api/locations/fair-oaks-adult-activity-center/faxes","services_url":"http://ohana-api-test.herokuapp.com/api/locations/fair-oaks-adult-activity-center/services","url":"http://ohana-api-test.herokuapp.com/api/locations/fair-oaks-adult-activity-center","address":{"id":1,"street":"2600
        Middlefield Road","city":"Redwood City","state":"CA","zip":"94063"},"organization":{"id":1,"name":"Peninsula
        Family Service","slug":"peninsula-family-service","urls":[],"url":"http://ohana-api-test.herokuapp.com/api/organizations/peninsula-family-service","locations_url":"http://ohana-api-test.herokuapp.com/api/organizations/peninsula-family-service/locations"},"phones":[{"id":1,"department":null,"extension":null,"number":"650
        780-7525","number_type":null,"vanity_number":null}]}]'
    http_version: 
  recorded_at: Sat, 05 Jul 2014 10:41:35 GMT
recorded_with: VCR 2.9.2
