---
http_interactions:
- request:
    method: get
    uri: http://ohana-api-test.herokuapp.com/api/search?action=index&api_token=<API_TOKEN>&controller=organizations&keyword=asdfg&location=&service_area=&utf8=%E2%9C%93
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/vnd.ohanapi-v1+json
      User-Agent:
      - Ohanakapa Ruby Gem 1.0.0
      X-Api-Token:
      - "<API_TOKEN>"
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 200
      message: OK
    headers:
      Cache-Control:
      - max-age=0, private, must-revalidate
      Content-Type:
      - application/json
      Date:
      - Tue, 29 Apr 2014 06:29:33 GMT
      Etag:
      - '"d751713988987e9331980363e24189ce"'
      Link:
      - <http://ohana-api-test.herokuapp.com/api/search?action=index&api_token=<API_TOKEN>&controller=organizations&keyword=asdfg&location=&page=0&service_area=&utf8=%E2%9C%93>;
        rel="last"
      Server:
      - nginx/1.4.7 + Phusion Passenger 4.0.40
      Status:
      - 200 OK
      X-Powered-By:
      - Phusion Passenger 4.0.40
      X-Request-Id:
      - 414438dd-0f86-4bd5-b0b2-49cb42581ac8
      X-Runtime:
      - '0.018664'
      X-Total-Count:
      - '0'
      X-Total-Pages:
      - '0'
      Content-Length:
      - '2'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: "[]"
    http_version: 
  recorded_at: Tue, 29 Apr 2014 06:29:32 GMT
- request:
    method: get
    uri: http://ohana-api-test.herokuapp.com/api/search?action=index&api_token=<API_TOKEN>&controller=organizations&utf8=%E2%9C%93
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/vnd.ohanapi-v1+json
      User-Agent:
      - Ohanakapa Ruby Gem 1.0.0
      X-Api-Token:
      - "<API_TOKEN>"
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 200
      message: OK
    headers:
      Cache-Control:
      - max-age=0, private, must-revalidate
      Content-Type:
      - application/json
      Date:
      - Tue, 29 Apr 2014 06:29:34 GMT
      Link:
      - <http://ohana-api-test.herokuapp.com/api/search?action=index&api_token=<API_TOKEN>&controller=organizations&page=22&utf8=%E2%9C%93>;
        rel="last", <http://ohana-api-test.herokuapp.com/api/search?action=index&api_token=<API_TOKEN>&controller=organizations&page=2&utf8=%E2%9C%93>;
        rel="next"
      Server:
      - nginx/1.4.7 + Phusion Passenger 4.0.40
      Status:
      - 200 OK
      X-Current-Page:
      - '1'
      X-Next-Page:
      - '2'
      X-Powered-By:
      - Phusion Passenger 4.0.40
      X-Request-Id:
      - d9122582-3b51-4df0-8efb-08daffc2f078
      X-Runtime:
      - '0.022752'
      X-Total-Count:
      - '22'
      X-Total-Pages:
      - '22'
      Transfer-Encoding:
      - chunked
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: '[{"services":[{"id":23,"audience":"Second service and nonprofit businesses,
        the public, military facilities, schools and government entities","description":"[NOTE
        THIS IS NOT A REAL ORGANIZATION--THIS IS FOR TESTTING PURPOSES OF THIS ALPHA
        APP] Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent suscipit
        metus eu orci lobortis dictum. In hac habitasse platea dictumst. Vivamus vulputate,
        neque ut sodales gravida, lorem nunc pharetra ligula, ac cursus sem justo
        a sapien. Duis vitae vestibulum magna. Sed vel augue in justo rhoncus viverra.
        Nam ac felis a purus lobortis porttitor sit amet quis est. Suspendisse vulputate
        nisl quis nisi fermentum aliquet euismod at augue. Sed ultricies, purus dapibus
        tristique dictum, tortor mauris porttitor nulla, at porta nisl sem sed dolor.
        Proin ac hendrerit erat. Duis porta iaculis orci, eu euismod quam tristique
        in. Phasellus nec purus sit amet sapien volutpat egestas.","eligibility":"None","fees":"None,
        except for permits and photocopying. Cash, checks and credit cards accepted","how_to_apply":"Walk
        in or apply by phone or mail","name":"hasdfasf","urls":["http://www.example.com","http://www.example2.com"],"wait":"No
        wait to 2 weeks","funding_sources":["City","County","Federal","State"],"service_areas":["San
        Mateo County","Alameda County","Contra Costa County","Marin County","San Francisco
        County","Santa Clara County"],"keywords":["Ruby on Rails/MongoDB/Redis","FIFA
        World Cup"],"updated_at":"2014-04-18T12:49:47.850-07:00"},{"id":22,"audience":"Profit
        and nonprofit businesses, the public, military facilities, schools and government
        entities","description":"[NOTE THIS IS NOT A REAL ORGANIZATION--THIS IS FOR
        TESTTING PURPOSES OF THIS ALPHA APP] Lorem ipsum dolor sit amet, consectetur
        adipiscing elit. Praesent suscipit metus eu orci lobortis dictum. In hac habitasse
        platea dictumst. Vivamus vulputate, neque ut sodales gravida, lorem nunc pharetra
        ligula, ac cursus sem justo a sapien. Duis vitae vestibulum magna. Sed vel
        augue in justo rhoncus viverra. Nam ac felis a purus lobortis porttitor sit
        amet quis est. Suspendisse vulputate nisl quis nisi fermentum aliquet euismod
        at augue. Sed ultricies, purus dapibus tristique dictum, tortor mauris porttitor
        nulla, at porta nisl sem sed dolor. Proin ac hendrerit erat. Duis porta iaculis
        orci, eu euismod quam tristique in. Phasellus nec purus sit amet sapien volutpat
        egestas.","eligibility":"None","fees":"None, except for permits and photocopying.
        Cash, checks and credit cards accepted","how_to_apply":"Walk in or apply by
        phone or mail","name":"bazfoo","urls":["http://www.smchealth.org","http://www.example.com","http://www.example2.com"],"wait":"No
        wait to 2 weeks","funding_sources":["City","County","Federal","State"],"service_areas":["San
        Mateo County","Alameda County","Contra Costa County","Marin County","San Francisco
        County","Santa Clara County"],"keywords":["Ruby on Rails/MongoDB/Redis","FIFA
        World Cup"],"updated_at":"2014-04-18T12:49:47.791-07:00"}],"mail_address":{"id":21,"location_id":22,"attention":"Hella
        Fellas","street":"2013 Avenue of the fellows, Suite 100","city":"San Maceo","state":"VT","zip":"90210"},"hours":"Monday-Friday,
        8-5; Saturday, 10-6; Sunday 11-5","urls":["http://www.smchealth.org","http://www.example.com","http://www.example2.com"],"emails":["sanmaceo@co.sanmaceo.ca.us","maceo@parker.com"],"transportation":"SAMTRANS
        stops within 1 block","short_desc":"[NOTE THIS IS NOT A REAL ENTRY--THIS IS
        FOR TESTING PURPOSES OF THIS ALPHA APP]","url":"http://ohana-api-test.herokuapp.com/api/locations/22","phones":[{"id":21,"location_id":22,"number":"650
        372-6200","department":"Information"},{"id":22,"location_id":22,"number":"650
        372-6200","department":"Reservations"}],"contacts":[{"id":29,"location_id":22,"name":"Suzanne
        Badenhoop","title":"Board President"}],"id":"22","languages":["Chinese (Cantonese)","Chinese
        (Taiwanese)","Filipino (Tagalog)","Russian","Spanish"],"organization":{"id":8,"name":"SanMaceo
        Example Agency.","slug":"sanmaceo-example-agency","created_at":"2014-04-18T12:49:47.008-07:00","updated_at":"2014-04-18T12:49:47.918-07:00","url":"http://ohana-api-test.herokuapp.com/api/organizations/8","locations_url":"http://ohana-api-test.herokuapp.com/api/organizations/8/locations"},"updated_at":"2014-04-18T12:49:47.528-07:00","faxes":[{"id":21,"location_id":22,"number":"650
        627-8244"}],"address":{"id":21,"location_id":22,"street":"2013 Avenue of the
        fellows, Suite 100","city":"Burlington","state":"VT","zip":"05201"},"description":"[NOTE
        THIS IS NOT A REAL ORGANIZATION--THIS IS FOR TESTTING PURPOSES OF THIS ALPHA
        APP] Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent suscipit
        metus eu orci lobortis dictum. In hac habitasse platea dictumst. Vivamus vulputate,
        neque ut sodales gravida, lorem nunc pharetra ligula, ac cursus sem justo
        a sapien. Duis vitae vestibulum magna. Sed vel augue in justo rhoncus viverra.
        Nam ac felis a purus lobortis porttitor sit amet quis est. Suspendisse vulputate
        nisl quis nisi fermentum aliquet euismod at augue. Sed ultricies, purus dapibus
        tristique dictum, tortor mauris porttitor nulla, at porta nisl sem sed dolor.
        Proin ac hendrerit erat. Duis porta iaculis orci, eu euismod quam tristique
        in. Phasellus nec purus sit amet sapien volutpat egestas.","name":"San Maceo
        Agency","created_at":"2014-04-18T12:49:47.528-07:00","slug":"san-maceo-agency","longitude":-73.1968254,"latitude":42.878036,"coordinates":[-73.1968254,42.878036],"accessibility":["Disabled
        Restroom","Disabled Parking","Wheelchair"],"_score":null,"_type":"location","_index":"production-ohana_api","_version":null,"sort":[1397850587528],"highlight":null,"_explanation":null}]'
    http_version: 
  recorded_at: Tue, 29 Apr 2014 06:29:33 GMT
- request:
    method: get
    uri: http://ohana-api-test.herokuapp.com/api/search?action=index&api_token=<API_TOKEN>&controller=organizations&page=3
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/vnd.ohanapi-v1+json
      User-Agent:
      - Ohanakapa Ruby Gem 1.0.0
      X-Api-Token:
      - "<API_TOKEN>"
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 200
      message: OK
    headers:
      Cache-Control:
      - max-age=0, private, must-revalidate
      Content-Type:
      - application/json
      Date:
      - Tue, 29 Apr 2014 06:29:35 GMT
      Link:
      - <http://ohana-api-test.herokuapp.com/api/search?action=index&api_token=<API_TOKEN>&controller=organizations&page=1>;
        rel="first", <http://ohana-api-test.herokuapp.com/api/search?action=index&api_token=<API_TOKEN>&controller=organizations&page=2>;
        rel="prev", <http://ohana-api-test.herokuapp.com/api/search?action=index&api_token=<API_TOKEN>&controller=organizations&page=22>;
        rel="last", <http://ohana-api-test.herokuapp.com/api/search?action=index&api_token=<API_TOKEN>&controller=organizations&page=4>;
        rel="next"
      Server:
      - nginx/1.4.7 + Phusion Passenger 4.0.40
      Status:
      - 200 OK
      X-Current-Page:
      - '3'
      X-Next-Page:
      - '4'
      X-Powered-By:
      - Phusion Passenger 4.0.40
      X-Previous-Page:
      - '2'
      X-Request-Id:
      - f210bc79-292f-48cf-a0e8-14868f3aa20a
      X-Runtime:
      - '0.014056'
      X-Total-Count:
      - '22'
      X-Total-Pages:
      - '22'
      Content-Length:
      - '416'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: '[{"id":"20","organization":{"id":6,"name":"Location with no phone","slug":"location-with-no-phone","created_at":"2014-04-18T12:32:12.124-07:00","updated_at":"2014-04-18T12:32:12.475-07:00","url":"http://ohana-api-test.herokuapp.com/api/organizations/6","locations_url":"http://ohana-api-test.herokuapp.com/api/organizations/6/locations"},"services":[{"id":20,"updated_at":"2014-04-18T12:32:12.259-07:00"}],"updated_at":"2014-04-18T12:32:12.272-07:00","mail_address":{"id":20,"location_id":20,"attention":"","street":"puma","city":"fairfax","state":"VA","zip":"22031"},"description":"no
        phone","name":"Location with no phone","created_at":"2014-04-18T12:32:12.179-07:00","slug":"location-with-no-phone","short_desc":"no
        phone","url":"http://ohana-api-test.herokuapp.com/api/locations/20","kind":"Test","_score":null,"_type":"location","_index":"production-ohana_api","_version":null,"sort":[1397849532179],"highlight":null,"_explanation":null}]'
    http_version: 
  recorded_at: Tue, 29 Apr 2014 06:29:34 GMT
- request:
    method: get
    uri: http://ohana-api-test.herokuapp.com/api/search?action=index&api_token=<API_TOKEN>&controller=organizations&org_name=SanMaceo%20Example%20Agency.&utf8=%E2%9C%93
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/vnd.ohanapi-v1+json
      User-Agent:
      - Ohanakapa Ruby Gem 1.0.0
      X-Api-Token:
      - "<API_TOKEN>"
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 200
      message: OK
    headers:
      Cache-Control:
      - max-age=0, private, must-revalidate
      Content-Type:
      - application/json
      Date:
      - Tue, 29 Apr 2014 06:29:36 GMT
      Server:
      - nginx/1.4.7 + Phusion Passenger 4.0.40
      Status:
      - 200 OK
      X-Current-Page:
      - '1'
      X-Powered-By:
      - Phusion Passenger 4.0.40
      X-Request-Id:
      - 159504b8-d815-4115-82dc-440fa231cab3
      X-Runtime:
      - '0.019590'
      X-Total-Count:
      - '1'
      X-Total-Pages:
      - '1'
      Transfer-Encoding:
      - chunked
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: '[{"services":[{"id":23,"audience":"Second service and nonprofit businesses,
        the public, military facilities, schools and government entities","description":"[NOTE
        THIS IS NOT A REAL ORGANIZATION--THIS IS FOR TESTTING PURPOSES OF THIS ALPHA
        APP] Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent suscipit
        metus eu orci lobortis dictum. In hac habitasse platea dictumst. Vivamus vulputate,
        neque ut sodales gravida, lorem nunc pharetra ligula, ac cursus sem justo
        a sapien. Duis vitae vestibulum magna. Sed vel augue in justo rhoncus viverra.
        Nam ac felis a purus lobortis porttitor sit amet quis est. Suspendisse vulputate
        nisl quis nisi fermentum aliquet euismod at augue. Sed ultricies, purus dapibus
        tristique dictum, tortor mauris porttitor nulla, at porta nisl sem sed dolor.
        Proin ac hendrerit erat. Duis porta iaculis orci, eu euismod quam tristique
        in. Phasellus nec purus sit amet sapien volutpat egestas.","eligibility":"None","fees":"None,
        except for permits and photocopying. Cash, checks and credit cards accepted","how_to_apply":"Walk
        in or apply by phone or mail","name":"hasdfasf","urls":["http://www.example.com","http://www.example2.com"],"wait":"No
        wait to 2 weeks","funding_sources":["City","County","Federal","State"],"service_areas":["San
        Mateo County","Alameda County","Contra Costa County","Marin County","San Francisco
        County","Santa Clara County"],"keywords":["Ruby on Rails/MongoDB/Redis","FIFA
        World Cup"],"updated_at":"2014-04-18T12:49:47.850-07:00"},{"id":22,"audience":"Profit
        and nonprofit businesses, the public, military facilities, schools and government
        entities","description":"[NOTE THIS IS NOT A REAL ORGANIZATION--THIS IS FOR
        TESTTING PURPOSES OF THIS ALPHA APP] Lorem ipsum dolor sit amet, consectetur
        adipiscing elit. Praesent suscipit metus eu orci lobortis dictum. In hac habitasse
        platea dictumst. Vivamus vulputate, neque ut sodales gravida, lorem nunc pharetra
        ligula, ac cursus sem justo a sapien. Duis vitae vestibulum magna. Sed vel
        augue in justo rhoncus viverra. Nam ac felis a purus lobortis porttitor sit
        amet quis est. Suspendisse vulputate nisl quis nisi fermentum aliquet euismod
        at augue. Sed ultricies, purus dapibus tristique dictum, tortor mauris porttitor
        nulla, at porta nisl sem sed dolor. Proin ac hendrerit erat. Duis porta iaculis
        orci, eu euismod quam tristique in. Phasellus nec purus sit amet sapien volutpat
        egestas.","eligibility":"None","fees":"None, except for permits and photocopying.
        Cash, checks and credit cards accepted","how_to_apply":"Walk in or apply by
        phone or mail","name":"bazfoo","urls":["http://www.smchealth.org","http://www.example.com","http://www.example2.com"],"wait":"No
        wait to 2 weeks","funding_sources":["City","County","Federal","State"],"service_areas":["San
        Mateo County","Alameda County","Contra Costa County","Marin County","San Francisco
        County","Santa Clara County"],"keywords":["Ruby on Rails/MongoDB/Redis","FIFA
        World Cup"],"updated_at":"2014-04-18T12:49:47.791-07:00"}],"mail_address":{"id":21,"location_id":22,"attention":"Hella
        Fellas","street":"2013 Avenue of the fellows, Suite 100","city":"San Maceo","state":"VT","zip":"90210"},"hours":"Monday-Friday,
        8-5; Saturday, 10-6; Sunday 11-5","urls":["http://www.smchealth.org","http://www.example.com","http://www.example2.com"],"emails":["sanmaceo@co.sanmaceo.ca.us","maceo@parker.com"],"transportation":"SAMTRANS
        stops within 1 block","short_desc":"[NOTE THIS IS NOT A REAL ENTRY--THIS IS
        FOR TESTING PURPOSES OF THIS ALPHA APP]","url":"http://ohana-api-test.herokuapp.com/api/locations/22","phones":[{"id":21,"location_id":22,"number":"650
        372-6200","department":"Information"},{"id":22,"location_id":22,"number":"650
        372-6200","department":"Reservations"}],"contacts":[{"id":29,"location_id":22,"name":"Suzanne
        Badenhoop","title":"Board President"}],"id":"22","languages":["Chinese (Cantonese)","Chinese
        (Taiwanese)","Filipino (Tagalog)","Russian","Spanish"],"organization":{"id":8,"name":"SanMaceo
        Example Agency.","slug":"sanmaceo-example-agency","created_at":"2014-04-18T12:49:47.008-07:00","updated_at":"2014-04-18T12:49:47.918-07:00","url":"http://ohana-api-test.herokuapp.com/api/organizations/8","locations_url":"http://ohana-api-test.herokuapp.com/api/organizations/8/locations"},"updated_at":"2014-04-18T12:49:47.528-07:00","faxes":[{"id":21,"location_id":22,"number":"650
        627-8244"}],"address":{"id":21,"location_id":22,"street":"2013 Avenue of the
        fellows, Suite 100","city":"Burlington","state":"VT","zip":"05201"},"description":"[NOTE
        THIS IS NOT A REAL ORGANIZATION--THIS IS FOR TESTTING PURPOSES OF THIS ALPHA
        APP] Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent suscipit
        metus eu orci lobortis dictum. In hac habitasse platea dictumst. Vivamus vulputate,
        neque ut sodales gravida, lorem nunc pharetra ligula, ac cursus sem justo
        a sapien. Duis vitae vestibulum magna. Sed vel augue in justo rhoncus viverra.
        Nam ac felis a purus lobortis porttitor sit amet quis est. Suspendisse vulputate
        nisl quis nisi fermentum aliquet euismod at augue. Sed ultricies, purus dapibus
        tristique dictum, tortor mauris porttitor nulla, at porta nisl sem sed dolor.
        Proin ac hendrerit erat. Duis porta iaculis orci, eu euismod quam tristique
        in. Phasellus nec purus sit amet sapien volutpat egestas.","name":"San Maceo
        Agency","created_at":"2014-04-18T12:49:47.528-07:00","slug":"san-maceo-agency","longitude":-73.1968254,"latitude":42.878036,"coordinates":[-73.1968254,42.878036],"accessibility":["Disabled
        Restroom","Disabled Parking","Wheelchair"],"_score":null,"_type":"location","_index":"production-ohana_api","_version":null,"sort":[1397850587528],"highlight":null,"_explanation":null}]'
    http_version: 
  recorded_at: Tue, 29 Apr 2014 06:29:35 GMT
recorded_with: VCR 2.9.0
