---
http_interactions:
- request:
    method: get
    uri: http://ohana-api-test.herokuapp.com/api/search?action=index&controller=organizations&keyword=asdfg&location=&utf8=%E2%9C%93
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/vnd.ohanapi-v1+json
      User-Agent:
      - Ohanakapa Ruby Gem 1.1.1
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 200
      message: OK
    headers:
      Cache-Control:
      - max-age=0, private, must-revalidate
      Content-Type:
      - application/json; charset=utf-8
      Date:
      - Wed, 16 Jul 2014 08:16:20 GMT
      Link:
      - <http://ohana-api-test.herokuapp.com/api/search?keyword=asdfg&location=&page=0&utf8=%E2%9C%93>;
        rel="last"
      Server:
      - nginx/1.6.0 + Phusion Passenger 4.0.45
      Status:
      - 200 OK
      X-Content-Type-Options:
      - nosniff
      X-Frame-Options:
      - SAMEORIGIN
      X-Powered-By:
      - Phusion Passenger 4.0.45
      X-Request-Id:
      - 2a8fb77f-810c-4e76-a26a-9db8f1123e82
      X-Runtime:
      - '0.015765'
      X-Total-Count:
      - '0'
      X-Total-Pages:
      - '0'
      X-Xss-Protection:
      - 1; mode=block
      Content-Length:
      - '34'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: "[]"
    http_version: 
  recorded_at: Wed, 16 Jul 2014 08:16:20 GMT
- request:
    method: get
    uri: http://ohana-api-test.herokuapp.com/api/search?action=index&controller=organizations&org_name=Salvation%20Army&utf8=%E2%9C%93
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/vnd.ohanapi-v1+json
      User-Agent:
      - Ohanakapa Ruby Gem 1.1.1
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 200
      message: OK
    headers:
      Cache-Control:
      - max-age=0, private, must-revalidate
      Content-Type:
      - application/json; charset=utf-8
      Date:
      - Wed, 16 Jul 2014 08:16:20 GMT
      Link:
      - <http://ohana-api-test.herokuapp.com/api/search?org_name=Salvation+Army&page=4&utf8=%E2%9C%93>;
        rel="last", <http://ohana-api-test.herokuapp.com/api/search?org_name=Salvation+Army&page=2&utf8=%E2%9C%93>;
        rel="next"
      Server:
      - nginx/1.6.0 + Phusion Passenger 4.0.45
      Status:
      - 200 OK
      X-Content-Type-Options:
      - nosniff
      X-Current-Page:
      - '1'
      X-Frame-Options:
      - SAMEORIGIN
      X-Next-Page:
      - '2'
      X-Powered-By:
      - Phusion Passenger 4.0.45
      X-Request-Id:
      - b6045046-5ce9-4ada-b863-6e90500e9442
      X-Runtime:
      - '0.086075'
      X-Total-Count:
      - '4'
      X-Total-Pages:
      - '4'
      X-Xss-Protection:
      - 1; mode=block
      Content-Length:
      - '879'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: '[{"id":14,"admin_emails":[],"coordinates":[-122.231539,37.49144],"description":"Provides
        food, clothing, bus tokens and shelter to individuals and families in times
        of crisis from the Redwood City Corps office and community centers throughout
        the county.   Administers Project REACH (Relief for Energy Assistance through
        Community Help) funds to prevent energy shut-off through a one-time payment.
        Counseling and translation services (English/Spanish) are available either
        on a walk-in basis or by appointment. Rental assistance with available funds.
        Another office (described separately) is located at 409 South Spruce Avenue,
        South San Francisco (650-266-4591).","latitude":37.49144,"longitude":-122.231539,"name":"Redwood
        City Corps","short_desc":"Provides a variety of emergency services to low-income
        persons. Also sponsors recreational and educational activities.","slug":"redwood-city-corps","updated_at":"2014-05-09T20:49:18.943-07:00","urls":["http://www.tsagoldenstate.org"],"contacts_url":"http://ohana-api-test.herokuapp.com/api/locations/redwood-city-corps/contacts","faxes_url":"http://ohana-api-test.herokuapp.com/api/locations/redwood-city-corps/faxes","services_url":"http://ohana-api-test.herokuapp.com/api/locations/redwood-city-corps/services","url":"http://ohana-api-test.herokuapp.com/api/locations/redwood-city-corps","address":{"id":14,"street":"660
        Veterans Blvd.","city":"Redwood City","state":"CA","zip":"94063"},"organization":{"id":4,"name":"Salvation
        Army","slug":"salvation-army","urls":[],"url":"http://ohana-api-test.herokuapp.com/api/organizations/salvation-army","locations_url":"http://ohana-api-test.herokuapp.com/api/organizations/salvation-army/locations"},"phones":[{"id":14,"department":null,"extension":null,"number":"650
        368-4643","number_type":null,"vanity_number":null}]}]'
    http_version: 
  recorded_at: Wed, 16 Jul 2014 08:16:20 GMT
recorded_with: VCR 2.9.2
