# First, copy this file to a new one called "application.yml" in the same
# config directory.

# This file is used by the "figaro" gem to allow you to store and use
# environment variables in the app without having to set them via the
# command line each time you run the app in development.
# Read more about figaro here: https://github.com/laserlemon/figaro

# Note that changes to this file will require a server restart to take effect.

# Each entry sets a local environment variable and overrides ENV variables
# in the Unix shell. For example, setting:
# OHANA_API_ENDPOINT: https://ohana-api-demo.herokuapp.com/api
# makes "https://ohana-api-demo.herokuapp.com/api" available as
# ENV["OHANA_API_ENDPOINT"] in the app. See config/initializers/ohanapi.rb
# for a usage example.

# Set this to the URL for your instance of the Ohana API:
# https://github.com/codeforamerica/ohana-api
# This environment variable is required.
OHANA_API_ENDPOINT: https://ohana-api-demo.herokuapp.com/api

# This setting is used for the Google translation feature.
# The "DOMAIN_NAME" environment variable should be set to your app's
# domain name, without the "www" subdomain, unless you're using a Heroku
# domain, in which case you should set it to your full Heroku domain name,
# such as "ohana-web-search-demo.herokuapp.com".
# If you have a custom domain name, like "www.smc-connect.org", that
# means setting it to "smc-connect.org".
#
# In development, it should only be set to a 2-level domain name,
# like "lvh.me", or "myapp.dev" if you're using Pow.
# Translation won't work with "localhost", so please open the site
# locally via http://lvh.me:{port number}
#
# Read more about lvh.me here:
# http://matthewhutchinson.net/2011/1/10/configuring-subdomains-in-development-with-lvhme
# Pow should work too if you prefer that: http://pow.cx/
DOMAIN_NAME: lvh.me

# If you choose to turn on rate limiting in your instance of Ohana API,
# obtain an API Token for this app from the developer portal of the API,
# then replace "changeme" with the actual token below.
# OHANA_API_TOKEN: changeme

# If the page has been translated to a language other than English
# and you would like your users to be able to type in search keywords
# in that language, you will need to sign up for a paid
# Google Translate API account that will allow the language detection feature.
# For pricing details and getting started with obtaining your API key,
# please visit: https://developers.google.com/translate/v2/pricing.
# Once you obtain your API key, uncomment translation-related code in
# app/controllers/locations_controller and enter your API key below to
# test the translation in development.
# GOOGLE_TRANSLATE_API_KEY: Your_API_Key

# To allow users to customize the translations on your site, include a
# Google Translate Customization website code. This code is used to verify
# ownership for the Google Website Translator so that custom translations are
# saved for the site. The tag appears in the HTML head and looks like this:
# <meta name="google-translate-customization" content="Your Website Code." />
#
# This code is generated by adding your site to your Google Account
# via the Google Website Translator Gadget Wizard at
# https://translate.google.com/manager/website/
# and clicking "Get Code" when prompted.
# GOOGLE_TRANSLATE_CUSTOMIZATION_CODE: Your_Website_Code_from_Google

# If you have a Google Analytics account you want to use to track visits
# to this app, set your ID and domain name below.
# An example ID is 'UA-40905632-1', and an example domain is 'smc-connect.org'.
# Note that you must have a Universal Analytics property for tracking to work.
# https://support.google.com/analytics/answer/4457764?hl=en
# GOOGLE_ANALYTICS_ID:
# GOOGLE_ANALYTICS_DOMAIN:

# While not required, using a Google Maps API key enables you to monitor your
# application's Maps API usage. If your usage exceeds Google's usage limits,
# you must load the Maps API using an API key in order to purchase more quota.
# Visit the following URL for more information and to setup an API key:
# https://developers.google.com/maps/documentation/javascript/tutorial#api_key
# GOOGLE_MAPS_API_KEY:

# When you visit a location, for example,
# http://ohana-web-search-demo.herokuapp.com/locations/salvation-army/sunnyvale-corps,
# the 'Last updated' time that is displayed at the bottom right of the page is
# set to UTC by default. If you would like to set it to a more appropriate
# time zone where most of your visitors live, you can set the 'TZ' environment
# variable to one of the accepted values:
# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones.
# For example, to set the time zone to Eastern Time, you would set the 'TZ'
# value below to 'America/New_York'.
# TZ:

# If you are using a custom domain name, set CANONICAL_URL to your preferred
# domain name, such as 'example.org' or 'www.example.org'.
# See config/environments/production.rb for more details.
# CANONICAL_URL:

###############################################################################
#
# SETTINGS FOR TESTS. PLEASE DO NOT MODIFY UNLESS YOU KNOW WHAT YOU ARE DOING.
#
###############################################################################

test:
  OHANA_API_ENDPOINT: http://ohana-api-test.herokuapp.com/api
  OHANA_API_TOKEN: ~
  DOMAIN_NAME: lvh.me
  GOOGLE_TRANSLATE_API_KEY: ~
