# This file is used by the "figaro" gem to allow you to store and use
# environment variables in the app without having to set them via the
# command line each time you run the app in development. Another advantage
# is that you can make changes in a production environment (such as Heroku)
# by simply changing the value of the environment variable, as opposed to
# making code changes and having to push them to apply the new setting.
# Read more about figaro here: https://github.com/laserlemon/figaro

# Note that changes to this file will require a server restart to take effect.

# Each entry sets a local environment variable and overrides ENV variables
# in the Unix shell. For example, setting:
# OHANA_API_ENDPOINT: https://ohana-api-demo.herokuapp.com/api
# makes "https://ohana-api-demo.herokuapp.com/api" available as
# ENV['OHANA_API_ENDPOINT'] in the app. See config/initializers/ohanapi.rb
# for a usage example.

# Below, you will find descriptions for each variable, followed by default
# settings for the development, production, and test environments.

####################################
#
# ENVIRONMENT VARIABLE DESCRIPTIONS
#
####################################

##############################################
#
# CANONICAL_URL - REQUIRED FOR CUSTOM DOMAINS
#
##############################################
# If you are using a custom domain name, set CANONICAL_URL to your preferred
# domain name, such as 'example.org' or 'www.example.org'.
# See config/environments/production.rb for more details.

########################################
#
# ENABLE_HTTPS - REQUIRED IN PRODUCTION
#
########################################
# When using the default Heroku domain setup (http://app-name.herokuapp.com),
# you can take advantage of SSL for free. However, to use SSL with a custom
# domain name, you'll need to do some work first, as explained in the Wiki:
# http://git.io/vez1W

################################
#
# OHANA_API_ENDPOINT - REQUIRED
#
################################
# Set this to the URL for your instance of the Ohana API:
# https://github.com/codeforamerica/ohana-api

################################
#
# OHANA_API_TOKEN - OPTIONAL
#
################################
# If you choose to turn on rate limiting in your instance of Ohana API,
# obtain an API Token for this app from the developer portal of the API,
# then replace "changeme" with the actual token.

#################################################
#
# GOOGLE_ANALYTICS_ID - OPTIONAL
# GOOGLE_ANALYTICS_DOMAIN - OPTIONAL
#
#################################################
# If you have a Google Analytics account you want to use to track visits
# to this app, set your ID and domain name below.
# An example ID is 'UA-40905632-1', and an example domain is 'smc-connect.org'.
# Note that you must have a Universal Analytics property for tracking to work.
# https://support.google.com/analytics/answer/4457764?hl=en

#################################################
#
# GOOGLE_MAPS_API_KEY - REQUIRED
#
#################################################
# A Google Maps API key is now required as of June 11, 2018, as well as enabling
# billing in your Google Cloud Platform account. New pricing goes into effect on
# July 16, 2018. For more details, visit:
# https://cloud.google.com/maps-platform/pricing/sheet/

###########################
#
# SETTINGS FOR DEVELOPMENT
#
###########################
development:
  # GOOGLE_MAPS_API_KEY:
  OHANA_API_ENDPOINT: https://ohana-api-demo.herokuapp.com/api
  # OHANA_API_TOKEN: changeme

###############################################################################
#
# SETTINGS FOR PRODUCTION.
#
# Run `figaro heroku:set -e production -a your_app_name` to set them on Heroku.
#
###############################################################################
production:
  # CANONICAL_URL:
  ENABLE_HTTPS: 'yes'
  # GOOGLE_ANALYTICS_ID:
  # GOOGLE_ANALYTICS_DOMAIN:
  GOOGLE_MAPS_API_KEY: changeme
  OHANA_API_ENDPOINT: https://ohana-api-demo.herokuapp.com/api
  # OHANA_API_TOKEN: changeme
  RAILS_LOG_TO_STDOUT: 'true'
  RAILS_SERVE_STATIC_FILES: 'true'

###############################################################################
#
# SETTINGS FOR TESTS. PLEASE DO NOT MODIFY UNLESS YOU KNOW WHAT YOU ARE DOING.
#
###############################################################################

test:
  CANONICAL_URL: lvh.me
  OHANA_API_ENDPOINT: http://ohana-api-test.herokuapp.com/api
  OHANA_API_TOKEN: ~
