# This file is used by the "figaro" gem to allow you to store and use
# environment variables in the app without having to set them via the
# command line each time you run the app in development. Another advantage
# is that you can make changes in a production environment (such as Heroku)
# by simply changing the value of the environment variable, as opposed to
# making code changes and having to push them to apply the new setting.
# Read more about figaro here: https://github.com/laserlemon/figaro

# Note that changes to this file will require a server restart to take effect.

# Each entry sets a local environment variable and overrides ENV variables
# in the Unix shell. For example, setting:
# OHANA_API_ENDPOINT: https://ohana-api-demo.herokuapp.com/api
# makes "https://ohana-api-demo.herokuapp.com/api" available as
# ENV['OHANA_API_ENDPOINT'] in the app. See config/initializers/ohanapi.rb
# for a usage example.

# Below, you will find descriptions for each variable, followed by default
# settings for the development, production, and test environments.

####################################
#
# ENVIRONMENT VARIABLE DESCRIPTIONS
#
####################################

##############################################
#
# CANONICAL_URL - REQUIRED FOR CUSTOM DOMAINS
#
##############################################
# If you are using a custom domain name, set CANONICAL_URL to your preferred
# domain name, such as 'example.org' or 'www.example.org'.
# See config/environments/production.rb for more details.

################################################
#
# DOMAIN_NAME - REQUIRED FOR GOOGLE TRANSLATION
#
################################################
# This setting is used for the Google translation feature.
# The "DOMAIN_NAME" environment variable should be set to your app's
# domain name, without the "www" subdomain, unless you're using a Heroku
# domain, in which case you should set it to your full Heroku domain name,
# such as "ohana-web-search-demo.herokuapp.com".
# If you have a custom domain name, like "www.smc-connect.org", that
# means setting it to "smc-connect.org".
#
# In development, it should only be set to a 2-level domain name,
# like "lvh.me", or "myapp.dev" if you're using Pow.
# Translation won't work with "localhost", so please open the site
# locally via http://lvh.me:{port number}
#
# Read more about lvh.me here:
# http://matthewhutchinson.net/2011/1/10/configuring-subdomains-in-development-with-lvhme
# Pow should work too if you prefer that: http://pow.cx/

########################################
#
# ENABLE_HTTPS - REQUIRED IN PRODUCTION
#
########################################
# When using the default Heroku domain setup (http://app-name.herokuapp.com),
# you can take advantage of SSL for free. However, to use SSL with a custom
# domain name, you'll need to do some work first, as explained in the Wiki:
# http://git.io/vez1W

################################
#
# OHANA_API_ENDPOINT - REQUIRED
#
################################
# Set this to the URL for your instance of the Ohana API:
# https://github.com/codeforamerica/ohana-api

################################
#
# OHANA_API_TOKEN - OPTIONAL
#
################################
# If you choose to turn on rate limiting in your instance of Ohana API,
# obtain an API Token for this app from the developer portal of the API,
# then replace "changeme" with the actual token.

######################################
#
# GOOGLE_TRANSLATE_API_KEY - OPTIONAL
#
######################################
# If the page has been translated to a language other than English
# and you would like your users to be able to type in search keywords
# in that language, you will need to sign up for a paid
# Google Translate API account that will allow the language detection feature.
# For pricing details and getting started with obtaining your API key,
# please visit: https://cloud.google.com/translate/v2/pricing.
# Once you obtain your API key, uncomment translation-related code in
# app/controllers/locations_controller and enter your API key below to
# test the translation in development.

#################################################
#
# GOOGLE_ANALYTICS_ID - OPTIONAL
# GOOGLE_ANALYTICS_DOMAIN - OPTIONAL
#
#################################################
# If you have a Google Analytics account you want to use to track visits
# to this app, set your ID and domain name below.
# An example ID is 'UA-40905632-1', and an example domain is 'smc-connect.org'.
# Note that you must have a Universal Analytics property for tracking to work.
# https://support.google.com/analytics/answer/4457764?hl=en

#################################################
#
# GOOGLE_MAPS_API_KEY - OPTIONAL
#
#################################################
# While not required, using a Google Maps API key enables you to monitor your
# application's Maps API usage. If your usage exceeds Google's usage limits,
# you must load the Maps API using an API key in order to purchase more quota.
# Visit the following URL for more information and to setup an API key:
# https://developers.google.com/maps/documentation/javascript/tutorial#api_key

###########################
#
# SETTINGS FOR DEVELOPMENT
#
###########################
development:
  DOMAIN_NAME: lvh.me
  # GOOGLE_MAPS_API_KEY:
  # GOOGLE_TRANSLATE_API_KEY: Your_API_Key
  OHANA_API_ENDPOINT: https://ohana-api-demo.herokuapp.com/api
  # OHANA_API_TOKEN: changeme

###############################################################################
#
# SETTINGS FOR PRODUCTION.
#
# Run `figaro heroku:set -e production -a your_app_name` to set them on Heroku.
#
###############################################################################
production:
  # CANONICAL_URL:
  DOMAIN_NAME: changeme
  ENABLE_HTTPS: 'yes'
  # GOOGLE_ANALYTICS_ID:
  # GOOGLE_ANALYTICS_DOMAIN:
  # GOOGLE_MAPS_API_KEY:
  # GOOGLE_TRANSLATE_API_KEY: Your_API_Key
  OHANA_API_ENDPOINT: https://ohana-api-demo.herokuapp.com/api
  # OHANA_API_TOKEN: changeme

###############################################################################
#
# SETTINGS FOR TESTS. PLEASE DO NOT MODIFY UNLESS YOU KNOW WHAT YOU ARE DOING.
#
###############################################################################

test:
  OHANA_API_ENDPOINT: http://ohana-api-test.herokuapp.com/api
  OHANA_API_TOKEN: ~
  DOMAIN_NAME: lvh.me
  GOOGLE_TRANSLATE_API_KEY: ~
