# These are the general links that appear on the homepage.
# The top-level `general` text needs to stay, but all other
# text can be edited to change what's shown on the homepage.
general :
  Government Assistance :
    - SNAP/Food Stamps
    - Health Insurance
    - Medicare
    - SFMNP/Food vouchers for seniors
    - WIC/Women, Infants, & Children

  Children, Teens, & Families :
    - Abuse Prevention
    - Child Care
    - Counseling
    - Discrimination
    - Mentoring Programs
    - Youth Development

# These are the priority links that appear on the homepage,
# which are styled with more emphasis than the general links.
# The top-level `priority` text needs to stay, but all other
# text can be edited to change what's shown on the homepage.
priority :
  Emergency :
    - Psychiatric Emergency
    - Emergency Food
    - Emergency Shelter
    - Hotlines

  Reporting :
    - Domestic Violence
    - Child Abuse
