# RequireJS configuration through the requirejs-rails gem.
#
# More information about RequireJS can be found at:
# http://requirejs.org.
# More information about the requirejs-rails gem can be found at:
# https://github.com/jwhitley/requirejs-rails.
# More information about the AMD module pattern can be found at:
# https://github.com/amdjs

# These module paths are located in app/assets/javascripts/routes/...
# Each one maps to a view in the application and ensures that only the needed
# JavaScript modules are run in a particular view.
modules:
  - name: 'routes/home/index'
  - name: 'routes/about/index'
  - name: 'routes/locations/index'
  - name: 'routes/locations/show'

# The paths to RequireJS plugins and 3rd party scripts.
paths:
  jquery: 'jquery-min'
  domReady: 'requirejs/domReady'
  gmapsOMS: 'google-maps/OverlappingMarkerSpiderfier'
  gmapsInfobox: 'google-maps/infobox'

# If you're including scripts that don't use the AMD module pattern and they
# have dependencies on each other, see the RequireJS configuration instructions
# for the 'shim' option at http://requirejs.org/docs/api.html#config-shim.
# shim:
#   'pathName':
#     dep: ['dependency','array']
#     exports: 'exportPathName'

# Finds require() dependencies inside a require() or define call and includes
# them in the optimizer that concatenates all the JavaScript modules together.
# See https://github.com/jrburke/r.js/blob/master/build/example.build.js
# for more information.
findNestedDependencies: true

# Needs to always be set to true for IE support.
# See http://requirejs.org/docs/api.html#ieloadfail
enforceDefine: true

# Amount of time to wait before timing out. Default is 7 seconds.
waitSeconds: 200