modules:
  - name: 'routes/home/index'
  - name: 'routes/about/index'
  - name: 'routes/organizations/index'
  - name: 'routes/organizations/show'

paths:
  jquery: 'jquery-min'
  domReady: 'requirejs/domReady'
  async: 'requirejs/async'
  enquire: 'enquire.min'
  modernizr: 'polyfills/modernizr.min'
  modernizrSelectors: 'polyfills/modernizr.selectors'
  checked: 'polyfills/checked-polyfill'
  classList: 'polyfills/remy/classList'
  addEventListener: 'polyfills/addEventListener'
  trim: 'polyfills/trim'

shim:
  'modernizrSelectors':
    dep: ['modernizr']
    exports: 'ModernizrSelectors'
  'checked':
    dep: ['jquery']
    exports: 'pfChecked'

# needs to always be set to true for IE support
# see http://requirejs.org/docs/api.html#ieloadfail
enforceDefine: true

# amount of time to wait before timing out. 7 seconds is default.
waitSeconds: 7